title: Branding Background
collated: true
variants:
  - name: color-theme-neutral
    context:
      theme: color-theme-neutral
  - name: color-theme-teal
    context:
      theme: color-theme-teal
  - name: questys
    context:
      theme: questys
