name: Fractal Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1

    - name: Install packages
      run: npm ci

    - name: Run npm build
      run: npm run build

    - name: Deploy to gh-pages
      with:
        publish_dir: ./build
